Repository osm-americana/openstreetmap-americana, pull requests merged in 2022-07, with the labels that each got.

#470 Add Uruguay shields
  doc-img/shield_map_world.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#468 Add shields for Venezuela
  doc-img/shield_map_world.svg
  icons/shield40_ve_t.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#473 Add shields for New Zealand urban roads
  src/js/shield_defs.js
Labels: internationalization, shields

#474 Add shields for Chile
  icons/shield40_cl_national_2.svg
  icons/shield40_cl_national_3.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#479 Add Chile to shield coverage world map
  doc-img/shield_map_world.svg
Labels: documentation, internationalization, shields

#485 Change CTRMA shield border to yellow
  src/js/shield_defs.js
Labels: shields

#490 Add shields for national routes of France
  src/js/shield_defs.js
Labels: internationalization, shields

#415 Blue hexagon shields for Pakistan National Highways
  doc-img/shield_map_world.svg
  icons/shield_hex_horz_blue_2.svg
  icons/shield_hex_horz_blue_3.svg
  icons/shield_pk_motorway.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#492 Add Turkish motorway shields
  doc-img/shield_map_world.svg
  icons/shield_hex_vert_orange.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#493 Add Armenia shields
  doc-img/shield_map_world.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#495 Remove unused trapezoid shield
  icons/shield_trapezoid_green_yellow_3.svg
  src/js/shield_defs.js
Labels: shields

#496 Add U.S. insular areas to shield coverage world map
  doc-img/shield_map_world.svg
  scripts/status_map.js
Labels: documentation

#504 Add airport, road construction to taginfo project file
  scripts/taginfo_template.json
Labels: documentation

#438 Icelandic shields
  doc-img/shield_map_world.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#505 Refactor some toll roads to generate styling with expressions
  src/americana.js
  src/constants/color.js
  src/layer/road.js
Labels: highway-lines

#506 Add bridges and tunnels to low-zoom Interstate highways
  src/layer/road.js
Labels: highway-lines

#510 Remove Interstate layer from high zoom
  src/layer/road.js
Labels: highway-lines

#511 Change label halo color for roads under construction
  src/layer/construction.js
Labels: highway-lines

#515 Add shields for New York parkways
  CONTRIBUTING.md
  icons/shield_us_ny_parkway_2.svg
  icons/shield_us_ny_parkway_3.svg
  icons/shield_us_ny_parkway_nyc.svg
  src/js/shield_defs.js
  src/layer/highway_shield.js
Labels: shields

#518 Data-driven styling of road and ferry labels
  src/americana.js
  src/layer/construction.js
  src/layer/ferry.js
  src/layer/road_label.js
  src/layer/transportation_label.js
Labels: highway-lines

#521 Add a console debug when plain shield will be used
  src/js/shield.js
Labels: shields

#523 Draw waterway labels before bridge, road labels
  src/americana.js
Labels: bug, highway-lines

#525 Combine shield layers and sort rendering
  src/americana.js
  src/layer/highway_shield.js
Labels: shields
