Repository osm-americana/openstreetmap-americana, pull requests merged in 2022-02, with the labels that each got.

#133 Add shield guidelines to contributor's guide
  README.md
  dev/README.md
  dev/americana.gpl
  doc-img/10_px_text.svg
  doc-img/12_px_text.svg
  doc-img/14_px_text.svg
  doc-img/16_px_text.svg
  doc-img/6_px_text.svg
  doc-img/8_px_text.svg
  doc-img/black.svg
  doc-img/pantone_116.svg
  doc-img/pantone_152.svg
  doc-img/pantone_187.svg
  doc-img/pantone_198.svg
  doc-img/pantone_259.svg
  doc-img/pantone_294.svg
  doc-img/pantone_342.svg
  doc-img/pantone_382.svg
  doc-img/pantone_469.svg
  doc-img/white.svg
  style/CONTRIBUTE.md
  style/icons/shield40_us_pa.svg
  style/icons/shield40_us_pa_turnpike.svg
Labels: documentation

#174 Ohio county road shields
  style/icons/shield40_us_oh_2.svg
  style/icons/shield40_us_oh_3.svg
  style/icons/shield40_us_oh_asd.svg
  style/icons/shield40_us_oh_sci_2.svg
  style/icons/shield40_us_oh_sci_3.svg
  style/js/shield_defs.js
Labels: shields

#161 Add American bannered shields
  style/js/shield_defs.js
Labels: shields

#179 Generate taginfo project file
  style/CONTRIBUTE.md
  style/js/screen_gfx.js
  style/package.json
  style/scripts/taginfo.js
  style/scripts/taginfo_template.json
Labels: documentation

#184 Road class and bridge/junction disambiguation
  style/layer/road.js
Labels: highway-lines

#183 Document more tags for taginfo
  style/CONTRIBUTE.md
  style/scripts/taginfo_template.json
Labels: documentation

#182 Remove extra padding from attribution logo
  style/configs/config.maptiler.js
Labels: bug

#187 Keep offset label style on primary at z14/15
  style/layer/road_label.js
Labels: bug

#189 Consolidate road label layers
  style/americana.js
  style/layer/road_label.js
Labels: highway-lines

#193 ROC route shields
  style/icons/shield40_tw_expressway.svg
  style/icons/shield40_tw_freeway.svg
  style/icons/shield40_tw_provincial.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#192 PRC and Hong Kong shields
  style/icons/shield40_cn_national_expressway_2.svg
  style/icons/shield40_cn_national_expressway_3.svg
  style/icons/shield40_cn_national_expressway_4.svg
  style/icons/shield40_cn_regional_expressway_2.svg
  style/icons/shield40_cn_regional_expressway_3.svg
  style/icons/shield40_cn_regional_expressway_4.svg
  style/icons/shield40_hk.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#190 Add Vietnam expressway shields
  style/js/shield_defs.js
Labels: internationalization, shields

#199 Prevent waterway label underlap
  style/americana.js
  style/layer/road_label.js
Labels: bug, highway-lines

#203 Thicken road label halo
  style/js/shield_text.js
  style/layer/road_label.js
Labels: highway-lines
