Repository osm-americana/openstreetmap-americana, pull requests merged in 2022-08, with the labels that each got.

#476 Add railroad tracks
  scripts/taginfo_template.json
  src/americana.js
  src/constants/color.js
  src/layer/rail.js
Labels: enhancement

#532 Convert some road styling to expressions
  src/americana.js
  src/layer/road.js
Labels: highway-lines

#534 Add shields for Mendocino County, California
  src/js/shield_defs.js
Labels: shields

#469 Add Texas outline shield
  icons/shield_us_tx_outline.svg
  src/js/shield_defs.js
Labels: shields

#535 Add shields for Branson, Missouri
  CONTRIBUTING.md
  src/js/shield_canvas_draw.js
  src/js/shield_defs.js
Labels: shields

#536 Add Kansas Turnpike shield
  icons/shield_us_ks_turnpike.svg
  src/js/shield_defs.js
Labels: shields

#529 Add shield for Western Ring Route in New Zealand
  src/js/shield_defs.js
Labels: internationalization, shields

#497 Add shields for Puerto Rico
  README.md
  doc-img/shield_map_us.svg
  doc-img/shield_map_world.svg
  icons/shield_escutcheon_2.svg
  icons/shield_escutcheon_3.svg
  icons/shield_escutcheon_blue_2.svg
  icons/shield_escutcheon_blue_3.svg
  icons/shield_escutcheon_rounded_2.svg
  icons/shield_escutcheon_rounded_3.svg
  icons/shield_escutcheon_yellow_2.svg
  scripts/blank_map_us.svg
  scripts/status_map.js
  src/js/shield_defs.js
Labels: shields

#542 Add shield for Lane County, Oregon
  src/js/shield_defs.js
Labels: shields

#545 Add bannered Tennessee route shields
  src/js/shield_defs.js
Labels: shields
