Repository osm-americana/openstreetmap-americana, pull requests merged in 2022-05, with the labels that each got.

#305 Enlarge diamond shield
  style/icons/shield40_diamond_white.svg
  style/icons/shield40_us_nc.svg
  style/js/shield_defs.js
Labels: shields

#243 Fix corrupted shields
  style/js/shield.js
  style/js/shield_canvas_draw.js
Labels: bug, shields

#309 Delete unused Japanese urban expressway shield
  style/icons/shield40_jp_urban_expressway.svg
Labels: internationalization, shields

#313 Add Truck-bannered North Carolina state routes
  style/js/shield_defs.js
Labels: shields

#310 Remove non-namespaced Croatian networks
  doc-img/shield_map_us.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#319 Add black and white oval shields for town maintained sections of Vermont routes
  style/js/shield_defs.js
Labels: shields

#318 Add airport styling
  style/americana.js
  style/constants/color.js
  style/icons/airport.svg
  style/icons/military_airport.svg
  style/layer/aeroway.js
Labels: enhancement

#327 Factor out pill shield function
  style/js/shield_canvas_draw.js
  style/js/shield_defs.js
  style/js/shield_text.js
Labels: shields

#337 Fix banner drop shadow overlapping shield
  style/js/shield.js
  style/js/shield_defs.js
  style/js/shield_text.js
Labels: shields

#334 Add styling for toll roads
  style/americana.js
  style/constants/color.js
  style/js/shield_defs.js
  style/layer/road.js
Labels: highway-lines

#342 Update OpenMapSamples to include toll renderings from #334.
  style/package-lock.json
Labels: openmaptiles
