Repository osm-americana/openstreetmap-americana, pull requests merged in 2022-03, with the labels that each got.

#211 Filter out disputed boundary lines
  style/layer/boundary.js
  style/scripts/taginfo_template.json
Labels: bug

#186 Add special case policy for ref parsing and banner employment
  style/CONTRIBUTE.md
  style/js/shield_canvas_draw.js
  style/js/shield_defs.js
Labels: documentation

#177 Ohio township road shields
  style/americana.js
  style/icons/shield40_us_oh_tus_salem.svg
  style/js/shield_defs.js
  style/layer/highway_shield.js
Labels: shields

#195 Philippines route shields
  style/icons/shield40_ph_expressway_2.svg
  style/icons/shield40_ph_national_2.svg
  style/icons/shield40_ph_national_3.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#223 Shields of Bangladesh
  style/js/shield_defs.js
Labels: internationalization, shields

#222 Shields of Malaysia
  style/icons/shield40_my.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#224 Shields of Nepal
  style/js/shield_defs.js
Labels: internationalization, shields

#228 Add shield for Indiana East-West Toll Road
  style/icons/shield40_us_in_toll.svg
  style/js/shield_defs.js
Labels: shields

#209 Generate maps of supported states, countries for shields
  README.md
  doc-img/shield_map_us.svg
  doc-img/shield_map_world.svg
  style/package.json
  style/scripts/blank_map_us.svg
  style/scripts/blank_map_world.svg
  style/scripts/status_map.js
Labels: documentation, enhancement

#226 Trans-Canada Highway shield
  doc-img/shield_map_world.svg
  style/icons/shield40_ca_tch.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#227 Shields of Alberta
  style/icons/shield40_home_down_white_2.svg
  style/icons/shield40_home_down_white_3.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#235 Put each region code on a separate line in status map CSS
  doc-img/shield_map_us.svg
  doc-img/shield_map_world.svg
  style/scripts/status_map.js
Labels: documentation, shields

#205 Texas shields
  doc-img/shield_map_us.svg
  style/icons/shield40_us_in_toll.svg
  style/js/shield_defs.js
Labels: shields

#250 add shield for US Virgin Islands
  doc-img/shield_map_us.svg
  style/js/shield_defs.js
Labels: shields

#257 added Guam and Northern Mariana Islands shields
  doc-img/shield_map_us.svg
  style/icons/shield40_us_gu_2.svg
  style/icons/shield40_us_gu_3.svg
  style/icons/shield40_us_mp_2.svg
  style/icons/shield40_us_mp_3.svg
  style/js/shield_defs.js
Labels: shields

#258 added American Samoa shields
  doc-img/shield_map_us.svg
  style/icons/shield40_us_as.svg
  style/js/shield_defs.js
Labels: shields

#256 Add state route highway shields for South Dakota
  doc-img/shield_map_us.svg
  style/icons/shield40_us_sd_2.svg
  style/icons/shield40_us_sd_3.svg
  style/js/shield_defs.js
Labels: shields
