Repository osm-americana/openstreetmap-americana, pull requests merged in 2022-12, with the labels that each got.

#593 Draw diamond and horizontal hexagon shields mathematically
  icons/shield_diamond.svg
  icons/shield_diamond_brown.svg
  icons/shield_hex_horz_blue_2.svg
  icons/shield_hex_horz_blue_3.svg
  src/js/shield_canvas_draw.js
  src/js/shield_defs.js
  src/js/shield_text.js
Labels: enhancement, shields

#601 Add business routes in Maine
  src/js/shield_defs.js
Labels: shields

#592 Gloss city names in the local language
  package-lock.json
  package.json
  src/americana.js
  src/constants/label.js
  src/layer/aeroway.js
  src/layer/park.js
  src/layer/place.js
  src/layer/transportation_label.js
  src/layer/water.js
  test/spec/label.js
Labels: enhancement, internationalization

#605 Nix `name:latin` fallback from English
  scripts/taginfo_template.json
  src/constants/label.js
  test/spec/label.js
Labels: bug, internationalization

#596 Indonesian national road shield
  doc-img/shield_map_world.svg
  icons/shield_id_national.svg
  src/js/shield_defs.js
  src/shieldtest.js
Labels: internationalization, shields

#607 Fix broken link in readme
  README.md
Labels: documentation

#609 Display which language codes are currently in use
  src/americana.js
  src/js/language_label.js
Labels: internationalization

#610 Waterlines
  scripts/taginfo_template.json
  src/americana.js
  src/constants/color.js
  src/layer/ferry.js
  src/layer/transportation_label.js
  src/layer/water.js
Labels: enhancement

#619 Fix street name localization
  src/layer/transportation_label.js
Labels: bug, internationalization, highway-lines

#635 Suppress shields for recreational TLA networks
  src/js/shield.js
  test/spec/shield.js
Labels: bug, shields

#640 Distinguish Greek national roads from motorways
  src/js/shield_defs.js
Labels: bug, internationalization, shields

#644 Draw octagon shields mathematically
  icons/shield_mx_mx.svg
  icons/shield_oct_green_2.svg
  icons/shield_oct_green_3.svg
  icons/shield_oct_green_4.svg
  src/js/shield_canvas_draw.js
  src/js/shield_defs.js
Labels: enhancement, shields

#633 Great Britain Motorway / Trunk shields
  CONTRIBUTING.md
  doc-img/shield_map_world.svg
  scripts/status_map.js
  src/js/shield_defs.js
Labels: openmaptiles, internationalization, shields
