Repository osm-americana/openstreetmap-americana, pull requests merged in 2022-11, with the labels that each got.

#562 Add Blue Ridge Parkway shield
  icons/shield_us_nps_brp.svg
  src/js/shield_defs.js
Labels: shields

#557 Iraq highway shields
  doc-img/shield_map_world.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#573 Shields of Algeria
  doc-img/shield_map_world.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#578 Use user-preferred language in labels
  scripts/taginfo_template.json
  src/constants/label.js
  src/layer/aeroway.js
  src/layer/park.js
  src/layer/place.js
  src/layer/transportation_label.js
  src/layer/water.js
Labels: enhancement, internationalization

#575 Haiti national, departmental route shields
  doc-img/shield_map_world.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#581 Localize labels dynamically
  src/americana.js
  src/constants/label.js
  src/layer/aeroway.js
  src/layer/park.js
  src/layer/place.js
  src/layer/transportation_label.js
  src/layer/water.js
Labels: enhancement, internationalization

#576 49-Mile Scenic Drive shield
  icons/shield_us_ca_sf_49.svg
  src/js/shield_defs.js
Labels: shields

#585 Draw trapezoid shields mathematically without SVGs
  icons/shield_trapezoid_2.svg
  icons/shield_trapezoid_3.svg
  icons/shield_trapezoid_black_yellow_2.svg
  icons/shield_trapezoid_black_yellow_3.svg
  icons/shield_trapezoid_blue_2.svg
  icons/shield_trapezoid_blue_3.svg
  icons/shield_trapezoid_green_yellow_2.svg
  icons/shield_trapezoid_rounded_brown_2.svg
  icons/shield_trapezoid_rounded_brown_3.svg
  src/js/shield_canvas_draw.js
  src/js/shield_defs.js
Labels: enhancement, shields

#590 Lazily load mapbox-gl-rtl-text plugin
  src/americana.js
Labels: bug, internationalization

#591 Draw home plate and vertical hexagon shields with math
  icons/shield_hex_vert_2.svg
  icons/shield_hex_vert_green_3.svg
  icons/shield_hex_vert_orange_3.svg
  icons/shield_hex_vert_yellow_3.svg
  icons/shield_home_2.svg
  icons/shield_home_3.svg
  icons/shield_home_blue_2.svg
  icons/shield_home_blue_3.svg
  icons/shield_home_blue_red_3.svg
  icons/shield_home_green_yellow_2.svg
  icons/shield_home_green_yellow_3.svg
  icons/shield_home_yellow_2.svg
  src/js/shield_canvas_draw.js
  src/js/shield_defs.js
  src/shieldtest.js
Labels: enhancement, shields
