Repository osm-americana/openstreetmap-americana, pull requests merged in 2022-06, with the labels that each got.

#348 Adjust straight-line elements of Alabama shields to pixel boundaries
  style/icons/shield40_us_al_2.svg
  style/icons/shield40_us_al_3.svg
Labels: shields

#345 create redirect
  CONTRIBUTING.md
Labels: documentation

#349 Add shield for Florida's Turnpike
  style/icons/shield40_us_fl_turnpike.svg
  style/js/shield_defs.js
Labels: shields

#361 Add shields for West Virginia 'county' roads
  style/js/shield_defs.js
Labels: shields

#360 Change colors and stroke widths of European shields
  style/icons/shield40_cz_2.svg
  style/icons/shield40_cz_prim_2.svg
  style/icons/shield40_hu_2.svg
  style/icons/shield40_it_2.svg
  style/icons/shield40_it_3.svg
  style/icons/shield40_it_4.svg
  style/icons/shield40_si_2.svg
  style/icons/shield40_un_e_2.svg
  style/icons/shield40_un_e_3.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#370 Adjust padding of US Interstate shield
  style/js/shield_defs.js
Labels: shields

#373 Reorder bridge layers to match other layers
  style/americana.js
Labels: highway-lines

#369 Shields: change default max font size to 14px
  style/CONTRIBUTE.md
  style/js/shield_defs.js
  style/js/shield_text.js
Labels: shields

#376 Add support for defining shields by ref
  style/CONTRIBUTE.md
  style/icons/shield40_ca_on_primary_qew.svg
  style/icons/shield40_us_ar_980.svg
  style/js/shield.js
  style/js/shield_canvas_draw.js
  style/js/shield_defs.js
Labels: enhancement, internationalization, shields

#139 Shields for European countries
  doc-img/shield_map_world.svg
  style/icons/shield40_ch_2.svg
  style/icons/shield40_hexagon_wide_green.svg
  style/icons/shield40_nl_city.svg
  style/icons/shield40_ro_trunk_2.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#383 Clarify and prioritize overall project purpose
  README.md
Labels: documentation

#365 Preliminary support for rendering Swedish shields
  style/js/shield_defs.js
Labels: internationalization, shields

#355 Change shield definitions for county and city highway networks
  style/icons/shield40_pentagon_blue_yellow_2.svg
  style/icons/shield40_pentagon_blue_yellow_3.svg
  style/icons/shield40_pentagon_green_white_2.svg
  style/icons/shield40_pentagon_green_white_3.svg
  style/icons/shield40_pentagon_white_pink_2.svg
  style/icons/shield40_pentagon_white_pink_3.svg
  style/icons/shield40_trapezoid_up_rounded_brown_2.svg
  style/icons/shield40_trapezoid_up_rounded_brown_3.svg
  style/js/shield_defs.js
Labels: shields

#394 Complete NL shields
  doc-img/shield_map_world.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#399 Contributing doc: Remove obsolete instruction for toll banners
  style/CONTRIBUTE.md
Labels: documentation

#401 Add Belgium shields
  doc-img/shield_map_world.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#400 Add AT Schnellstraße shield
  style/js/shield_defs.js
Labels: internationalization, shields

#395 Adjust pill shield padding
  style/js/shield_defs.js
  style/js/shield_text.js
Labels: shields

#409 Align Ontario shield to pixel boundaries
  icons/shield40_ca_on_primary.svg
  icons/shield40_ca_on_primary_qew.svg
  icons/shield40_ca_on_primary_toll.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#414 More detailed Vermont shields
  icons/shield40_us_vt_2.svg
  icons/shield40_us_vt_3.svg
  src/js/shield_defs.js
Labels: shields

#398 Updated CONTRIBUTE.md to reflect that project can run on Windows
  CONTRIBUTING.md
Labels: documentation

#420 Correct link
  README.md
Labels: documentation

#402 Add support for text halo in shields
  icons/shield40_ca_nb.svg
  icons/shield40_ca_nb_primary.svg
  icons/shield40_ca_nb_secondary.svg
  icons/shield40_us_ok_2.svg
  icons/shield40_us_ok_3.svg
  src/constants/color.js
  src/js/shield.js
  src/js/shield_canvas_draw.js
  src/js/shield_defs.js
  src/js/shield_text.js
  src/layer/background.js
  src/layer/road_label.js
Labels: shields

#427 Add shields for Kansas counties
  src/js/shield_defs.js
Labels: shields

#430 Mention wikidata in the project's documentation.
  README.md
Labels: documentation

#417 Åland shields
  src/js/shield_defs.js
Labels: internationalization, shields

#431 Add shield for Michigan M-185
  CONTRIBUTING.md
  icons/shield40_diamond_brown.svg
  src/js/shield_defs.js
Labels: shields

#432 Clarify documentation about special case shields
  CONTRIBUTING.md
Labels: documentation

#437 Add documentation for `textHaloColor`
  CONTRIBUTING.md
Labels: documentation

#439 Add Tennessee shields
  icons/shield40_us_tn_primary.svg
  icons/shield40_us_tn_secondary.svg
  src/js/shield_defs.js
Labels: shields

#444 Remove unused NCM shield for San Juan County, NM
  icons/shield40_pentagon_white_pink_2.svg
  src/js/shield_defs.js
Labels: shields

#441 Add Houston-area toll road shields
  CONTRIBUTING.md
  icons/shield40_home_down_blue_red_3.svg
  icons/shield40_pentagon_purple_yellow_3.svg
  icons/shield40_us_tx_fbctra.svg
  src/js/shield.js
  src/js/shield_defs.js
  src/layer/highway_shield.js
Labels: shields

#445 Add NJ county spur and truck route shields
  src/js/shield_defs.js
Labels: shields

#447 Improve support for Finnish shields
  src/js/shield_defs.js
Labels: internationalization, shields

#448 Add Chicago Skyway shield
  icons/shield40_us_il_skyway.svg
  src/js/shield_defs.js
Labels: shields

#449 Change spaces to underscores in Wisconsin county shield definitions
  src/js/shield_defs.js
Labels: shields

#454 Add New Zealand shields
  doc-img/shield_map_world.svg
  icons/shield40_nz_sh_2.svg
  icons/shield40_nz_sh_3.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#452 Add noref images to taginfo project file
  scripts/taginfo.js
Labels: bug, documentation, shields

#453 Update world shield coverage map
  doc-img/shield_map_world.svg
  scripts/status_map.js
Labels: bug, documentation, shields

#460 Add Ghana shields
  doc-img/shield_map_world.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#463 Add shields for Iran freeways
  doc-img/shield_map_world.svg
  src/js/shield_defs.js
Labels: internationalization, shields
