Repository osm-americana/openstreetmap-americana, pull requests merged in 2022-04, with the labels that each got.

#266 Render ferry routes
  style/americana.js
  style/layer/ferry.js
Labels: highway-lines

#269 Add British Columbia Shields
  style/icons/shield40_ca_bc_2.svg
  style/icons/shield40_ca_bc_3.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#271 Add Saskatchewan shields
  style/icons/shield40_ca_sk_secondary.svg
  style/icons/shield40_home_down_blue_2.svg
  style/icons/shield40_home_down_blue_3.svg
  style/icons/shield40_home_down_blue_inverted_2.svg
  style/icons/shield40_home_down_blue_inverted_3.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#273 Add Prince Edward Island shields
  style/icons/shield40_ca_pe.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#272 Add Manitoba shields
  style/icons/shield40_ca_mb_winnipeg.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#274 Add Nova Scotia shields
  style/icons/shield40_badge_2.svg
  style/icons/shield40_badge_3.svg
  style/icons/shield40_ca_ns_h.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#275 Add New Brunswick shields
  style/icons/shield40_ca_nb_primary.svg
  style/icons/shield40_ca_nb_secondary.svg
  style/icons/shield40_ca_nb_tertiary.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#283 Use colorLighten on black shield to draw Saskatchewan 'tertiary' shield
  style/icons/shield40_home_down_blue_inverted_2.svg
  style/icons/shield40_home_down_blue_inverted_3.svg
  style/js/shield_defs.js
Labels: shields

#279 Add place labels for villages
  style/americana.js
  style/layer/place.js
Labels: enhancement

#292 Clean up lingering inactive code & optimize NY STE shield
  style/icons/shield40_us_ny_ste.svg
  style/js/shield.js
  style/js/shield_defs.js
Labels: bug

#286 Add Arkansas shields
  doc-img/shield_map_us.svg
  style/icons/shield40_us_ar_2.svg
  style/icons/shield40_us_ar_3.svg
  style/js/shield_defs.js
Labels: shields

#284 Add Missouri shields
  doc-img/shield_map_us.svg
  style/icons/shield40_us_mo_2.svg
  style/icons/shield40_us_mo_3.svg
  style/js/shield_defs.js
Labels: shields

#288 Add Florida shields
  doc-img/shield_map_us.svg
  style/icons/shield40_us_fl_2.svg
  style/icons/shield40_us_fl_3.svg
  style/icons/shield40_us_fl_toll.svg
  style/js/shield_defs.js
Labels: shields

#294 Add Washington, DC shield
  doc-img/shield_map_us.svg
  style/icons/shield40_us_dc.svg
  style/js/shield_defs.js
Labels: shields

#297 Add wider variant for US county route shield
  style/icons/shield40_us_county_2.svg
  style/icons/shield40_us_county_3.svg
  style/js/shield_defs.js
Labels: shields

#298 Add shields for remaining New Jersey counties
  style/js/shield_defs.js
Labels: shields

#278 Add Ontario shields
  style/icons/shield40_ca_on_primary.svg
  style/icons/shield40_ca_on_primary_toll.svg
  style/icons/shield40_trapezoid_down_2.svg
  style/icons/shield40_trapezoid_down_3.svg
  style/icons/shield40_trapezoid_up_2.svg
  style/icons/shield40_trapezoid_up_3.svg
  style/icons/shield40_trapezoid_up_black_yellow_2.svg
  style/icons/shield40_trapezoid_up_black_yellow_3.svg
  style/icons/shield40_trapezoid_up_blue_white_2.svg
  style/icons/shield40_trapezoid_up_blue_white_3.svg
  style/icons/shield40_trapezoid_up_green_yellow_2.svg
  style/icons/shield40_trapezoid_up_green_yellow_3.svg
  style/js/shield_defs.js
Labels: internationalization, shields

#296 Add Oklahoma shields
  doc-img/shield_map_us.svg
  style/icons/shield40_us_ok_2.svg
  style/icons/shield40_us_ok_3.svg
  style/js/shield_defs.js
Labels: shields

#295 Add Maryland shields
  doc-img/shield_map_us.svg
  style/icons/shield40_us_md_2.svg
  style/icons/shield40_us_md_3.svg
  style/js/shield_defs.js
Labels: shields
