Repository osm-americana/openstreetmap-americana, pull requests merged in 2023-06, with the labels that each got.

#874 Add tile usage policy
  CONTRIBUTING.md
  README.md
  TILE_USAGE.md
Labels: documentation

#869 Aerialway station in taginfo
  scripts/taginfo_template.json
Labels: points of interest

#878 Migrate fonts to fontstack66 repo
  .cargo/config.toml
  CONTRIBUTING.md
  package.json
  scripts/FONTS.md
  scripts/fonts.js
  scripts/fonts.json
  scripts/generate_style.js
  scripts/stats.js
  src/americana.js
  src/configs/config.aws.js
Labels: build, performance, fonts

#512 Add oneway arrows to remaining highway classes
  icons/oneway.svg
  icons/oneway_black.svg
  icons/oneway_white.svg
  src/layer/index.js
  src/layer/oneway.js
  src/layer/transportation_label.js
Labels: highway-lines

#832 Add shield for John Hunt Morgan Heritage Trail in Ohio
  icons/shield_us_oh_jhmht.svg
  src/js/shield_defs.js
Labels: shields
