Repository osm-americana/openstreetmap-americana, pull requests merged in 2023-02, with the labels that each got.

#752 Add shields for Great Lakes Circle Tour routes
  CONTRIBUTING.md
  icons/shield_glct_lect.svg
  icons/shield_glct_lhct.svg
  icons/shield_glct_lmct.svg
  icons/shield_glct_loop_lmct.svg
  icons/shield_glct_lsct.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#756 Add Maine Turnpike shield
  icons/shield_us_me_turnpike.svg
  src/js/shield_defs.js
Labels: shields

#757 increase minimum width of diamond shields
  src/js/shield_canvas_draw.js
Labels: bug, shields

#727 Generate sample taginfo graphic for all networks
  package-lock.json
  package.json
  scripts/taginfo.js
  src/js/screen_gfx.js
  src/js/shield.js
Labels: documentation, shields

#764 Fix lightening of anti-aliased pixels
  icons/shield_glct_lmct.svg
  icons/shield_glct_loop_lmct.svg
  src/js/shield.js
  src/js/shield_defs.js
Labels: bug, shields

#765 Add Natchez Trace Parkway shield
  icons/shield_us_nps_ntp.svg
  src/js/shield_defs.js
Labels: shields

#773 Group shields in legend by highway system
  src/index.html
  src/js/legend_control.js
Labels: bug, shields

#774 Simulate `line-gap-width` in legend
  src/js/legend_control.js
Labels: bug, highway-lines

#784 Fix error when opening legend
  src/js/legend_control.js
Labels: bug, shields

#778 Add layer sorting for roads within a common layer
  src/layer/road.js
Labels: bug, highway-lines

#753 Label both sides of international boundaries
  src/constants/label.js
  src/layer/boundary.js
  src/layer/index.js
  test/spec/label.js
Labels: internationalization, boundaries

#783 Specify shield width in custom functions
  src/js/custom_shields.js
  src/js/shield_canvas_draw.js
Labels: bug, shields

#776 Runtime POI sprite colors
  CONTRIBUTING.md
  icons/poi_coffee_cup.svg
  icons/poi_health_cross.svg
  icons/poi_hospital.svg
  icons/poi_martini_glass.svg
  icons/poi_military_plane.svg
  icons/poi_p.svg
  icons/poi_plane.svg
  icons/poi_school.svg
  src/americana.js
  src/constants/color.js
  src/js/poi.js
  src/js/screen_gfx.js
  src/js/shield.js
  src/layer/aeroway.js
  src/layer/poi.js
Labels: points of interest

#797 Add Great Lakes Seaway Trail shield
  icons/shield_us_glst.svg
  src/js/shield_defs.js
Labels: shields
