Repository osm-americana/openstreetmap-americana, pull requests merged in 2023-12, with the labels that each got.

#999 Add gas stations
  icons/poi_fuel.svg
  scripts/taginfo_template.json
  src/layer/poi.js
Labels: enhancement, points of interest

#1009 Add shields for Ring of Antwerp, Belgium
  src/js/shield_defs.js
Labels: internationalization, shields

#1012 Add shields for Aruban road network
  src/js/shield_defs.js
Labels: internationalization, shields

#1013 Adding supermarket POI icon
  icons/poi_supermarket.svg
  scripts/taginfo_template.json
  src/layer/poi.js
Labels: enhancement, points of interest

#1019 Omit indigenous lands from park rendering
  src/layer/park.js
Labels: bug
