Repository osm-americana/openstreetmap-americana, pull requests merged in 2023-01, with the labels that each got.

#647 Restore green hexagon shield to test page
  src/shieldtest.js
Labels: bug, shields

#632 Generate legend on demand
  CONTRIBUTING.md
  README.md
  src/americana.js
  src/index.html
  src/js/legend_config.js
  src/js/legend_control.js
  src/js/shield_defs.js
  src/layer/aeroway.js
  src/layer/boundary.js
  src/layer/building.js
  src/layer/construction.js
  src/layer/ferry.js
  src/layer/highway_exit.js
  src/layer/highway_shield.js
  src/layer/landuse.js
  src/layer/park.js
  src/layer/place.js
  src/layer/rail.js
  src/layer/road.js
  src/layer/water.js
  test/spec/highway_shield.js
Labels: enhancement

#648 Replace pentagon shield icons with draw function
  icons/shield_pent_3.svg
  icons/shield_pent_blue_yellow_2.svg
  icons/shield_pent_blue_yellow_3.svg
  icons/shield_pent_brown_2.svg
  icons/shield_pent_brown_3.svg
  icons/shield_pent_green_2.svg
  icons/shield_pent_green_3.svg
  icons/shield_pent_purple_yellow_3.svg
  src/js/shield_canvas_draw.js
  src/js/shield_defs.js
  src/shieldtest.js
Labels: enhancement, shields

#666 Format semicolon-delimited value lists in labels
  src/constants/label.js
  src/index.html
  src/layer/highway_exit.js
  src/layer/transportation_label.js
  test/spec/label.js
Labels: enhancement, internationalization

#670 Deduplicate names in gloss; gloss towns
  src/constants/label.js
  src/layer/place.js
  test/spec/label.js
Labels: enhancement, internationalization

#671 Fix conversion from `fill-opacity` to CSS
  src/js/legend_control.js
Labels: bug

#669 Use inline delimiter in waterway labels
  src/layer/water.js
Labels: bug

#673 Split localized name on semicolons before gloss
  src/constants/label.js
  test/spec/label.js
Labels: bug, internationalization

#675 Add National Highway shields of India
  doc-img/shield_map_world.svg
  icons/shield_in_nh_2.svg
  icons/shield_in_nh_3.svg
  icons/shield_in_nh_4.svg
  src/js/shield_defs.js
  src/shieldtest.js
Labels: internationalization, shields

#667 Draw escutcheon shields mathematically
  icons/shield_escutcheon_2.svg
  icons/shield_escutcheon_3.svg
  icons/shield_escutcheon_blue_2.svg
  icons/shield_escutcheon_blue_3.svg
  icons/shield_escutcheon_rounded_2.svg
  icons/shield_escutcheon_rounded_3.svg
  icons/shield_escutcheon_yellow_2.svg
  src/js/shield_canvas_draw.js
  src/js/shield_defs.js
  src/shieldtest.js
Labels: enhancement, shields

#683 Filter out more transparent road, rail features from legend
  src/js/legend_control.js
  src/layer/road.js
Labels: bug

#689 Add school icons
  icons/poi_school.svg
  scripts/taginfo_template.json
  src/layer/poi.js
Labels: enhancement, points of interest

#695 Specify 1px knockout on POIs
  CONTRIBUTING.md
Labels: documentation, points of interest

#696 All routes for the UK and Ireland
  src/js/shield_defs.js
Labels: internationalization, shields

#700 Refactor utility functions out of shield definitions
  src/js/shield.js
  src/js/shield_defs.js
Labels: shields

#701 Convert roundedRectangle to JSON definition
  src/js/shield.js
  src/js/shield_canvas_draw.js
  src/js/shield_defs.js
Labels: enhancement, shields

#703 Change Latvia regional shield to blue
  src/js/shield_defs.js
Labels: bug, internationalization, shields

#702 Remove shields of Denmark, Hungary, Moldova, North Macedonia, Serbia
  doc-img/shield_map_world.svg
  icons/shield_ro_trunk_2.svg
  src/js/shield_defs.js
  src/shieldtest.js
Labels: bug, internationalization, shields

#705 Restore appearance of rounded rectangle shields
  src/js/shield_canvas_draw.js
  src/js/shield_defs.js
Labels: bug, shields

#706 Refactor circle/ellipse draw functions to JSON
  src/js/shield.js
  src/js/shield_canvas_draw.js
  src/js/shield_defs.js
Labels: enhancement, shields

#704 Change Bulgaria national shield to blue
  src/js/shield_defs.js
Labels: bug, internationalization, shields

#708 Refactor remaining shape draw functions to JSON
  src/americana.js
  src/js/custom_shields.js
  src/js/shield.js
  src/js/shield_canvas_draw.js
  src/js/shield_defs.js
Labels: enhancement, shields

#712 remove Denmark and Hungary from shield test page
  src/shieldtest.js
Labels: shields

#711 Improve diamond shield draw function
  src/js/shield_canvas_draw.js
Labels: bug, shields

#713 Add triangle shield draw function
  icons/shield_tri_rounded.svg
  src/js/shield_canvas_draw.js
  src/js/shield_defs.js
Labels: enhancement, shields

#721 change Mackinac Island shield to fixed-width
  src/js/shield_defs.js
Labels: bug, shields

#715 Use OMT rankings for POI deconfliction
  src/layer/poi.js
Labels: enhancement, points of interest

#722 Add Mass Pike shield
  icons/shield_us_ma_pike.svg
  src/js/shield_defs.js
Labels: shields

#697 Shield for German Bundesstraße
  doc-img/shield_map_world.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#726 Add config variable to outline shield text padding
  src/configs/config.aws.js
  src/configs/config.localhost.js
  src/configs/config.maptiler.js
  src/js/shield.js
Labels: enhancement, shields

#731 Distinguish Ohio Turnpike from Ohio state routes
  src/js/shield_defs.js
Labels: bug, shields

#676 India national expressway shield
  CONTRIBUTING.md
  src/js/shield.js
  src/js/shield_defs.js
  test/spec/shield.js
Labels: internationalization, shields

#714 Convert shield sprite definitions to JSON
  scripts/status_map.js
  scripts/taginfo.js
  src/americana.js
  src/js/shield.js
  src/js/shield_defs.js
  src/shieldtest.js
Labels: enhancement, shields

#729 Add performance monitoring to shieldtest
  src/shieldtest.html
  src/shieldtest.js
Labels: enhancement, shields

#733 Add Oklahoma Turnpike shield
  icons/shield_us_ok_turnpike.svg
  src/js/shield_defs.js
Labels: shields

#738 Add Lincoln Heritage Trail shield
  icons/shield_us_lht.svg
  src/js/shield_defs.js
Labels: shields

#732 add fishhead shield draw function
  icons/shield_fishhead_blue_2.svg
  icons/shield_fishhead_blue_3.svg
  icons/shield_fishhead_red_2.svg
  icons/shield_fishhead_red_3.svg
  src/js/shield_canvas_draw.js
  src/js/shield_defs.js
Labels: enhancement, shields

#737 Remove intermediate rasterization steps in shield drawing code
  package-lock.json
  package.json
  src/js/custom_shields.js
  src/js/shield.js
  src/js/shield_canvas_draw.js
  src/js/shield_defs.js
  src/shieldtest.js
Labels: enhancement, shields

#740 Add Lake Pontchartrain Causeway shield
  icons/shield_us_la_causeway.svg
  src/js/shield_defs.js
Labels: shields

#748 Add Ireland to shield status map
  doc-img/shield_map_world.svg
  scripts/status_map.js
Labels: bug, documentation, internationalization, shields

#750 Force shield canvas to cpu.
  src/js/screen_gfx.js
Labels: performance

#751 Fix local config path in .gitignore
  .gitignore
Labels: bug
