Repository osm-americana/openstreetmap-americana, pull requests merged in 2023-03, with the labels that each got.

#755 add aerialways
  scripts/taginfo_template.json
  src/constants/color.js
  src/js/legend_config.js
  src/layer/aerialway.js
  src/layer/index.js
  src/layer/transportation_label.js
Labels: enhancement

#817 Add Ohio & Erie Canalway shield
  icons/shield_us_oh_oec.svg
  src/js/shield_defs.js
Labels: shields

#818 Add CI for MacOS
  .github/workflows/test-build-mac.yml
  .github/workflows/test-build-ubuntu.yml
Labels: build

#823 Fix error resolving Kurdish country codes
  src/constants/label.js
Labels: bug, internationalization

#801 Render our own font stack
  .cargo/config.toml
  .gitignore
  ACKNOWLEDGEMENTS.md
  package-lock.json
  package.json
  scripts/FONTS.md
  scripts/fonts.js
  scripts/fonts.json
  src/js/style.js
  src/layer/aeroway.js
  src/layer/boundary.js
  src/layer/highway_exit.js
  src/layer/highway_shield.js
  src/layer/park.js
  src/layer/place.js
  src/layer/poi.js
  src/layer/transportation_label.js
  src/layer/water.js
Labels: internationalization

#829 Make font path absolute
  src/js/style.js
Labels: bug

#830 Update transport POI color to mauve
  CONTRIBUTING.md
  doc-img/pantone_234_c.svg
  src/constants/color.js
  src/layer/aeroway.js
Labels: documentation, points of interest

#816 Add Newfoundland and Labrador shields
  src/js/shield_defs.js
Labels: internationalization, shields

#831 Adjust line width on detailed shields
  icons/shield_us_dc.svg
  icons/shield_us_glst.svg
  icons/shield_us_in_toll.svg
  icons/shield_us_ks_turnpike.svg
  icons/shield_us_nj_ace_noref.svg
  icons/shield_us_nj_gsp_noref.svg
  icons/shield_us_ny_ste.svg
  icons/shield_us_ny_thruway.svg
  icons/shield_us_ok_2.svg
  icons/shield_us_ok_3.svg
  src/js/shield_defs.js
Labels: shields

#835 change Michigan State Trunkline Highway shield to variable-width
  src/js/shield_defs.js
Labels: bug, shields

#840 Relative glyph URLs
  scripts/generate_style.js
  scripts/stats.js
  src/americana.js
  src/js/style.js
Labels: build

#841 add Noto Sans Cherokee to font stack
  scripts/fonts.json
Labels: internationalization

#842 Change icon stroke width to 1px
  icons/poi_coffee_cup.svg
  icons/poi_health_cross.svg
  icons/poi_hospital.svg
  icons/poi_martini_glass.svg
  icons/poi_military_plane.svg
  icons/poi_p.svg
  icons/poi_plane.svg
  icons/poi_square_dot.svg
  icons/shield_us_az_2.svg
  icons/shield_us_az_3.svg
  icons/shield_us_mp_2.svg
  icons/shield_us_mp_3.svg
  icons/shield_us_ok_turnpike.svg
  icons/shield_us_wi_2.svg
  icons/shield_us_wi_3.svg
Labels: bug, shields
