Repository osm-americana/openstreetmap-americana, pull requests merged in 2023-04, with the labels that each got.

#847 revert April Fool's behavior
  src/americana.js
  src/js/shield.js
Labels: internationalization, shields

#843 Add diamond and triangle shield text constraints
  src/js/shield_defs.js
  src/js/shield_text.js
  src/shieldtest.js
Labels: enhancement, shields

#848 refactor POI layer to use both class and subclass
  src/layer/poi.js
Labels: points of interest

#845 Add bus and rail POIs for stops and stations
  icons/poi_bus.svg
  icons/poi_bus_circle.svg
  icons/poi_rail.svg
  icons/poi_rail_circle.svg
  scripts/taginfo_template.json
  src/layer/poi.js
Labels: enhancement, points of interest

#477 Add busways
  scripts/taginfo_template.json
  src/layer/index.js
  src/layer/road.js
  src/layer/road_label.js
  src/layer/transportation_label.js
Labels: enhancement, highway-lines

#807 Add town hall icon
  icons/poi_town_hall.svg
  scripts/taginfo_template.json
  src/layer/poi.js
Labels: points of interest

#852 add Swiss national route shields
  doc-img/shield_map_world.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#853 add bannered Michigan shields
  src/js/shield_defs.js
Labels: shields

#856 Railway halts should be styled like stations
  src/layer/poi.js
Labels: bug, points of interest

#854 Flip school icon
  icons/poi_school.svg
Labels: points of interest

#858 add missing combining characters and punctuation to font stack
  scripts/fonts.json
Labels: bug, internationalization

#857 Add museum icon and brown "attraction" POI color
  CONTRIBUTING.md
  icons/poi_museum.svg
  scripts/taginfo_template.json
  src/constants/color.js
  src/layer/poi.js
Labels: points of interest

#855 Add aerialway station icon
  icons/poi_aerialway_circle.svg
  src/layer/poi.js
Labels: points of interest

#859 hide bus and tram stop labels until very high zoom
  src/layer/poi.js
Labels: points of interest

#808 Through railways include branch lines
  src/layer/rail.js
Labels: bug
