Repository osm-americana/openstreetmap-americana, pull requests merged in 2023-10, with the labels that each got.

#916 Move shield definition helper functions to shield library
  .github/workflows/build-preview.yml
  .github/workflows/deploy.yml
  .gitignore
  package-lock.json
  package.json
  shieldlib/README.md
  shieldlib/package.json
  shieldlib/src/custom_shields.ts
  shieldlib/src/index.d.ts
  shieldlib/src/index.ts
  shieldlib/src/screen_gfx.ts
  shieldlib/src/shield.d.ts
  shieldlib/src/shield.js
  shieldlib/src/shield_canvas_draw.ts
  shieldlib/src/shield_helper.d.ts
  shieldlib/src/shield_helper.ts
  shieldlib/src/shield_renderer.d.ts
  shieldlib/src/shield_renderer.ts
  shieldlib/src/shield_text.ts
  shieldlib/src/types.d.ts
  shieldlib/src/types.ts
  src/js/shield_defs.js
Labels: enhancement, shield-generator

#941 Per-shield banner colors
  shieldlib/README.md
  shieldlib/src/custom_shields.ts
  shieldlib/src/shield.js
  shieldlib/src/shield_banner.ts
  shieldlib/src/shield_canvas_draw.ts
  shieldlib/src/shield_helper.d.ts
  shieldlib/src/shield_helper.ts
  shieldlib/src/shield_renderer.ts
  shieldlib/src/shield_text.mjs
  shieldlib/src/shield_text.ts
  shieldlib/src/types.d.ts
  shieldlib/src/types.ts
  shieldlib/tsconfig.json
  src/js/shield_defs.js
Labels: enhancement, shield-generator

#965 Change shield font to Noto Sans Condensed
  icons/shield_ca_mb_winnipeg.svg
  icons/shield_ca_ns_h.svg
  icons/shield_ca_on_primary.svg
  icons/shield_ca_tch.svg
  icons/shield_ca_tch_2.svg
  icons/shield_ca_tch_3.svg
  icons/shield_in_nh_2.svg
  icons/shield_in_nh_3.svg
  icons/shield_in_nh_4.svg
  icons/shield_kr_expressway_2.svg
  icons/shield_kr_expressway_3.svg
  icons/shield_us_fl_toll.svg
  icons/shield_us_ut_2.svg
  icons/shield_us_ut_3.svg
  scripts/build.ts
  shieldlib/README.md
  shieldlib/src/screen_gfx.ts
  shieldlib/src/shield_helper.ts
  src/fonts.css
  src/index.html
  src/js/shield_defs.js
  src/shieldtest.html
  src/shieldtest.js
Labels: shields

#974 add bannered South Dakota shields
  src/js/shield_defs.js
Labels: shields

#975 Remove PR preview files when PRs are closed
  .github/workflows/deploy-pr-checks.yml
  .github/workflows/s3-cleanup.yml
Labels: build

#972 limit oneway arrows to currently supported highway features
  src/layer/oneway.js
Labels: bug, highway-lines

#973 add shields for Albany County, Wyoming
  src/js/shield_defs.js
Labels: shields

#983 add shields for Custer State Park, South Dakota
  icons/shield_us_sd_csp.svg
  src/constants/color.js
  src/js/shield_defs.js
  src/shieldtest.js
Labels: shields

#982 add South Dakota secondary shields
  src/js/shield_defs.js
Labels: shields
