Repository osm-americana/openstreetmap-americana, pull requests merged in 2024-09, with the labels that each got.

#1073 Allow ShieldJSON to specify a map of banners on a base shield instead of requiring separate entries
  shieldlib/README.md
  shieldlib/src/shield_renderer.ts
  shieldlib/src/types.ts
  src/js/shield_defs.js
Labels: shield-generator

#1153 Adding POI icon for restaurants and fast food
  icons/poi_restaurant.svg
  src/layer/poi.js
Labels: enhancement, points of interest

#1154 add shields for Nevada County, California
  src/js/shield_defs.js
Labels: shields

#1158 Restore Historic US Route shield
  src/js/shield_defs.js
Labels: bug, shields

#1159 Update retagged shield definitions
  src/js/shield_defs.js
Labels: bug, internationalization, shields

#1162 Add shield for Utah Federal Aid routes
  src/js/shield_defs.js
Labels: shields
