Repository osm-americana/openstreetmap-americana, pull requests merged in 2024-12, with the labels that each got.

#1176 Add shields for Arapahoe and Jefferson Counties, Colorado
  src/js/shield_defs.js
Labels: shields

#1173 Fix banner definitions for several route networks [BUGFIX]
  src/js/shield_defs.js
Labels: bug, shields

#1177 Add shields for Clear Creek County, Colorado
  src/js/shield_defs.js
Labels: shields

#1179 Remove padding from the default shield for unknown networks
  src/js/shield_defs.js
Labels: bug, shield-generator
