Repository osm-americana/openstreetmap-americana, pull requests merged in 2024-07, with the labels that each got.

#1120 Replace National Historic Trail shields with triangular color swatches
  icons/shield_us_nht_oreg.svg
  icons/shield_us_nht_ovvi.svg
  icons/shield_us_nht_semo.svg
Labels: shields

#1131 Update GitHub Pages URLs
  CONTRIBUTING.md
  scripts/extract_layer.js
  scripts/folder_diff.ts
  scripts/generate_style.js
  scripts/stats.js
  scripts/taginfo.js
  shieldlib/README.md
Labels: build

#1134 Update GitHub Pages URLs for glyphs
  scripts/extract_layer.js
  scripts/generate_style.js
  scripts/stats.js
  src/js/map_builder.ts
Labels: build

#1143 Fixing Broken Wikipedia link
  README.md
Labels: documentation
