Repository osm-americana/openstreetmap-americana, pull requests merged in 2024-05, with the labels that each got.

#1054 Highlight Aruba on shield coverage map
  doc-img/shield_map_world.svg
Labels: documentation

#1049 Add Halifax bridge shields
  icons/shield_ca_ns_s_mdb.svg
  icons/shield_ca_ns_s_mkb.svg
  src/js/shield_defs.js
Labels: enhancement, internationalization, shields

#1046 assign Minnesota counties correct shields
  src/js/shield_defs.js
Labels: shields

#1057 Add various missing bannered shields in the US
  src/js/shield_defs.js
Labels: shields

#1056 Add shields for Croatia
  doc-img/shield_map_world.svg
  src/js/shield_defs.js
Labels: enhancement, internationalization, shields

#1060 Add Hanford Site routes
  src/js/shield_defs.js
Labels: shields

#1061 Add convenience links to published artifacts
  README.md
Labels: documentation, enhancement

#1063 Convert shield.js to typescript
  shieldlib/src/shield.ts
  shieldlib/src/shield_canvas_draw.ts
  shieldlib/src/shield_helper.ts
  shieldlib/src/shield_renderer.ts
  shieldlib/src/shield_text.ts
  shieldlib/src/types.d.ts
  shieldlib/src/types.ts
  src/americana.js
  src/bare_americana.js
  src/debug_config.ts
  src/js/map_builder.ts
  src/shieldtest.js
Labels: enhancement, shield-generator

#1072 Upgrade the lint GitHub action
  .github/workflows/lint.yml
Labels: bug, build

#1070 Allow hard-coded ref values in shield definitions
  CONTRIBUTING.md
  shieldlib/README.md
  shieldlib/src/shield.ts
  shieldlib/src/types.ts
Labels: enhancement, shield-generator

#1066 Add missing types to ShieldDefinition
  doc-img/shield_map_world.svg
  shieldlib/src/shield.ts
  shieldlib/src/types.ts
Labels: shield-generator

#1076 Move text on US interstate shields down 1 pixel
  src/js/shield_defs.js
Labels: bug, shields

#1075 Add compressed size for ShieldJSON and StyleJSON artifacts
  scripts/stats.js
  scripts/stats_compare.js
Labels: enhancement, build

#1077 Fix copy/paste typo on compressed JSON CI comparison
  scripts/stats_compare.js
Labels: bug, build

#1069 Make dedicated pill shape function
  scripts/taginfo.js
  shieldlib/README.md
  shieldlib/src/shield_canvas_draw.ts
  shieldlib/src/shield_helper.ts
  test/sample_locations.json
Labels: enhancement, shield-generator

#1080 Add shields for expressways in Ontario, Canada
  icons/shield_ca_on_hamilton_blue.svg
  icons/shield_ca_on_hamilton_green.svg
  icons/shield_ca_on_toronto.svg
  src/js/shield_defs.js
  src/shieldtest.js
Labels: internationalization, shields

#1079 Add Turkish state highway shields
  src/js/shield_defs.js
Labels: internationalization, shields

#1078 Add icons for capitals of admin_level 5 and 6
  icons/place_dot_in_circle.svg
  src/layer/place.js
Labels: enhancement

#1083 Replace Utah shield icons
  icons/shield_us_ut_2.svg
  icons/shield_us_ut_3.svg
  src/js/shield_defs.js
Labels: shields
