Repository osm-americana/openstreetmap-americana, pull requests merged in 2024-06, with the labels that each got.

#1084 Add shield for network=US:I:Spur
  src/js/shield_defs.js
Labels: enhancement, shields

#1085 Add shields for Alabama beach express highways
  icons/shield_us_al_foley.svg
  src/js/shield_defs.js
Labels: enhancement, shields

#1086 Assign shield icons based on ref length
  shieldlib/README.md
  shieldlib/src/shield.ts
Labels: bug, shield-generator

#1087 feat: add Regional boundaries (`admin_level=5`)
  src/layer/boundary.js
  src/layer/index.js
Labels: enhancement, boundaries

#1068 Add shield for Inner Loop, Rochester, NY
  src/js/shield_defs.js
  src/shieldtest.js
Labels: shields

#1089 Add Niger national route shields
  doc-img/shield_map_world.svg
  src/js/shield_defs.js
Labels: enhancement, internationalization, shields

#1088 Add Madagascar national route shields
  doc-img/shield_map_world.svg
  src/js/shield_defs.js
Labels: enhancement, internationalization, shields

#1090 run npm update
  package-lock.json
Labels: build

#1081 Refactor all special case shield definitions inline
  src/js/shield_defs.js
Labels: shields

#1099 maplibre-shield-generator v0.0.6
  shieldlib/package.json
Labels: build, shield-generator

#1098 Add shields for Ejes Viales of Mexico City
  icons/shield_mx_cdmx_eje_central.svg
  icons/shield_mx_cdmx_eje_nte.svg
  icons/shield_mx_cdmx_eje_ote.svg
  icons/shield_mx_cdmx_eje_pte.svg
  icons/shield_mx_cdmx_eje_sur.svg
  src/js/shield_defs.js
Labels: enhancement, internationalization, shields

#1107 Add support for Faroe Islands shields
  doc-img/shield_map_world.svg
  src/js/shield_defs.js
Labels: enhancement, internationalization, shields

#1092 update package-lock.json
  package-lock.json
Labels: build

#1108 Add French departmental and metropolitan route shields
  doc-img/shield_map_world.svg
  scripts/status_map.js
  src/js/shield_defs.js
Labels: enhancement, internationalization, shields

#1097 Add shields for states of Mexico
  icons/shield_mx_state_2.svg
  icons/shield_mx_state_3.svg
  src/js/shield_defs.js
  src/shieldtest.js
Labels: enhancement, internationalization, shields

#1096 Replace shield icons for Mexican federal highways
  icons/shield_mx_mx.svg
  icons/shield_mx_mx_2.svg
  icons/shield_mx_mx_3.svg
  icons/shield_mx_mx_4.svg
  shieldlib/src/shield.ts
  src/js/shield_defs.js
  src/shieldtest.html
  src/shieldtest.js
  test/spec/shield.js
Labels: enhancement, internationalization, shields

#1113 bump github action versions to hush warnings
  .github/workflows/deploy-pr-checks.yml
Labels: build
