Repository osm-americana/openstreetmap-americana, pull requests merged in 2024-04, with the labels that each got.

#1034 Add Bookstores
  icons/shield_us_az_scenic.svg
  scripts/taginfo_template.json
  src/layer/poi.js
  test/sample_locations.json
Labels: enhancement, points of interest

#1040 add county-assigned US National Park shields
  src/js/shield_defs.js
Labels: shields

#1039 add Weld County Parkway shield
  src/js/shield_defs.js
Labels: shields

#1032 Rename shield image names based on structured route properties
  src/configs/config.aws.js
  src/js/shield_format.ts
  src/layer/highway_shield.js
  test/shield_format/shield_format.spec.ts
  test/spec/highway_shield.js
  test/spec/shield.js
Labels: openmaptiles, shields, planetiler, shield-generator

#912 Add shields for Nova Scotia scenic drives
  icons/shield_ca_ns_s_bdolsd.svg
  icons/shield_ca_ns_s_cet.svg
  icons/shield_ca_ns_s_ct.svg
  icons/shield_ca_ns_s_dnisd.svg
  icons/shield_ca_ns_s_et.svg
  icons/shield_ca_ns_s_fdlt.svg
  icons/shield_ca_ns_s_gt.svg
  icons/shield_ca_ns_s_ksd.svg
  icons/shield_ca_ns_s_lr.svg
  icons/shield_ca_ns_s_md.svg
  icons/shield_ca_ns_s_mt.svg
  icons/shield_ca_ns_s_st.svg
  src/js/shield_defs.js
Labels: internationalization, shields

#1042 change shields of Lincoln and Rock Counties, Minnesota
  src/js/shield_defs.js
  src/layer/highway_shield.js
  test/spec/highway_shield.js
Labels: bug, shields

#1044 add shields for Sierra County, CA and Washington County, UT
  src/js/shield_defs.js
Labels: enhancement, shields

#1045 add Mississippi Scenic Route shields
  src/js/shield_defs.js
Labels: enhancement, shields

#1047 update shield defs that use refsByName
  src/js/shield_defs.js
Labels: bug, shields

#1022 Universities from z10
  src/layer/poi.js
Labels: enhancement, points of interest, planetiler

#1007 Add additional statistics to PR checks tab
  scripts/stats.js
  scripts/stats_compare.js
Labels: enhancement, build

#1052 Force MacOS CI runner to x86_64
  .github/workflows/test-build-macos-13.yml
Labels: bug, build

#323 Add Zia sun symbol for New Mexico shield
  icons/shield40_us_nm_2.svg
  icons/shield40_us_nm_3.svg
  scripts/stats_compare.js
  src/js/shield_defs.js
  src/layer/poi.js
Labels: shields
