Repository osm-americana/openstreetmap-americana, pull requests merged in 2025-02, with the labels that each got.

#1192 Remove shield for Purchase Parkway (Kentucky)
  src/js/shield_defs.js
Labels: shields

#1196 Upgrade maplibre-gl
  package-lock.json
  package.json
  scripts/generate_style.js
Labels: build

#1183 Widen highways at very high zoom
  src/layer/road.js
  src/layer/transportation_label.js
Labels: enhancement, highway-lines

#1198 Add shields for Weld County, Colorado
  src/js/shield_defs.js
Labels: shields
