Repository osm-americana/openstreetmap-americana, pull requests merged in 2025-01, with the labels that each got.

#1182 make triangle shield more rounded
  shieldlib/src/shield_helper.ts
Labels: enhancement, shields

#1180 overrideByName causes legend to omit shields #1165
  package-lock.json
  src/js/legend_control.js
Labels: bug

#1157 Add a hillshade layer
  package-lock.json
  package.json
  src/americana.js
  src/constants/color.js
  src/js/hillshade_control.js
  src/js/style.js
  src/layer/hillshade.js
  src/layer/index.js
Labels: enhancement

#1190 maplibre-shield-generator v0.1.0
  shieldlib/package.json
Labels: build, shield-generator

#1178 Adding highway shields in Peru
  doc-img/shield_map_world.svg
  icons/shield_escutcheon_crossbar_2.svg
  icons/shield_escutcheon_crossbar_3.svg
  icons/shield_pe_2.svg
  icons/shield_pe_3.svg
  src/js/shield_defs.js
Labels: internationalization, shields
